### PR TITLE
Fix invalid HTML

### PR DESCRIPTION
**Pull request by dave1010**
Octocat likes valid markup.

### CODE REVIEW

**Comment by cqr** [comment]
Hey actually this is not valid HTML, it's valid XHTML. In HTML, the &lt;img&gt; tag doesn't close.

You're still right, but I would rather see them move to &lt;!DOCTYPE html&gt;

**Comment by dave1010** [comment]
Very true. Though you could argue that XHTML is a type of HTML. I was just validating against the existing doctype. Changing it to `<!DOCTYPE html>` is a good idea.

**Comment by Monoverde888** [comment]
uh

**Review by ivan-developer-01 — APPROVED** [review]

**Review by ivan-developer-01 — APPROVED** [review]
URL unshort

**Comment by GreenePetal** [comment]
..

**Comment by creeper12356** [comment]
wow First PR..

**Pull request merged**
