### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by noodlylight**
Commit the spoon

### CODE REVIEW

**Comment by noodlylight** [comment]
and again?

**Comment by noodlylight** [comment]
and again?

**Comment by ANARCHIST2014** [comment]
And again an again!

**Comment by ANARCHIST2014** [comment]
How do I get a profile pic

**Comment by RUZAC** [comment]
HOW,I DONT KNOW... MAVYBE A LITTLE CHIP ENHANCEMENT..
TRY EXEL D55PCTALBRR..

**Pull request closed without merging**
