### PR TITLE
Ritesh

### PR DESCRIPTION
**Pull request by RiM1604**

### CODE REVIEW

**Comment by AbdulRahmanIlyas** [comment]
Ok

**Comment by AbdulRahmanIlyas** [comment]
I have not received any project reloant payment Kindly any payment I
received is ok or can be credited to my account.

**Comment by AbdulRahmanIlyas** [comment]
I didn't release the old projects from which they were running, they got
deleted automatically, kindle them also continue again and the payment
received should be in OKX.

**Review by Qdotagba — COMMENTED** [review]
Hey

**Review by Qdotagba — COMMENTED** [review]
Hey

**Comment by Qdotagba** [comment]
> Ok
> 
> 
>

**Comment by Qdotagba** [comment]
> Hey

**Pull request closed without merging**
