### PR TITLE
Update index.html and styles.css

### PR DESCRIPTION
**Pull request by SzymonForysiukPW**
Addressing #1
This pull request includes changes to the index.html and styles.css files to introduce a new feature: the Octocat image and a welcome message. The changes include the addition of a new div element with an id of octocat in the index.html file, and corresponding CSS styles in the styles.css file.
Key changes:
index.html: Added a new div element with an id of octocat that contains an image of the Octocat and a welcome message.
styles.css: Added new CSS styles for the test class, the body element, and the octocat id. The octocat id styles specifically target the img element within it, setting its display to block and controlling its width and height.

### CODE REVIEW

**Review by SzymonForysiukPW — COMMENTED** [review]
Apprived

**Review by SzymonForysiukPW — COMMENTED** [review]
Apprived

**Comment by SzymonForysiukPW** [comment]
test

**Comment by Nordtom** [comment]
Wallet

**Pull request closed without merging**
