### PR TITLE
Create test about your favorite food.md

### PR DESCRIPTION
**Pull request by noodleCYF**
just a test of a pull request in the spoon-knife repository. 
Tell us your favorite food now. Mine choice is noodle, all types of noodles, including fast instant noodle.
What about yours?

### CODE REVIEW

**Comment by Olivier2685** [comment]
my favorites are raw meats....hummmmmm ; )

**Comment by UNIVAC-Coder** [comment]
I like food, most all foods.  Mostly meat.

**Comment by ssaaaddiiaaa** [comment]
I like sweets

**Comment by jafarsaad** [comment]
Mie asianfood

**Pull request closed without merging**
