### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KidiIT**
Made a change on the README.md

### CODE REVIEW

**Comment by KidiIT** [comment]
I Made a change on the README.md @KidiIT

**Review by KidiIT — COMMENTED** [review]
Comparison

**Review by KidiIT — COMMENTED** [review]
Approved✔️✔️

**Comment by KidiIT** [comment]
Reviewed and approved✔️

**Review by KidiIT — COMMENTED** [review]
Reviewed and approved✔️✔️

**Comment by KidiIT** [comment]
All reviewed and approved❤️💡

**Review by KidiIT — COMMENTED** [review]
Reviewed and approved all staged changes❤️🫶🤓

**Review by KidiIT — COMMENTED** [review]
Approved❤️🤓

**Review by T9ipa — APPROVED** [review]

**Review by KidiIT — COMMENTED** [review]
All reviewed and approved🫶❤️

**Comment by KidiIT** [comment]
All checked and approved🙌❤️

**Comment by KidiIT** [comment]
All reviewed and approved all new changes. Thank you and you're welcome

**Pull request closed without merging**
