### PR TITLE
Put the silverware to use.

### PR DESCRIPTION
**Pull request by kloassie**
Whats on the menu?

Just a spoon, a knife and even a fork is nothing to a hungry person. 
Hunger will make a bear dance. A monkey too, btw...

Klaas van der Horn

### CODE REVIEW

**Comment by kloassie** [comment]
Spaghetti?? What kinda Dutchman are you? ' Should be good ol' hutspot!

**Comment by kloassie** [comment]
What kinda dutchman I am? A flying one, that has his spelling capitalization as well.

**Comment by kloassie** [comment]
Pfff... Spelling schmelling...

**Comment by kloassie** [comment]
Wow this is one he*\* of a popular thread!

**Comment by kloassie** [comment]
Not really... Just some di**head who thinks too much of himself, thus creating an overload of comments on his own commit...

**Comment by kloassie** [comment]
Ah yeah - now I see. Talk about ego.

**Comment by bcasiello** [comment]
I won't comment on the ego, but I can definitely advocate for the spaghetti!
+1 vote to pull this commit.

**Pull request closed without merging**
